sudo: required

services:
  - docker

language: go

python:
  - '3.5'

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -e $DOCKER_EMAIL -p $DOCKER_PASS
  - export REPO=cookkkie/mee6
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:latest
  - docker push $REPO
