sudo: required
services:
  - docker
language: python
python:
  - '3.5'
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
before_install:
  - docker login -e $DOCKER_EMAIL -p $DOCKER_PASS
  - export REPO=cookkkie/mee6
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:latest
script:
  - echo "Ok"
after_success:
  - docker push $REPO
